### ISSUE TITLE
Responders dependency should be in the gemspec

### ISSUE THREAD

**Issue by mamhoff** [omnistegan/solidus_responders#1]
When requiring this gem, we want the dependency on the `responders` gem to be passed on to the host app. For that, it has to be added to the Gemspec and can then be removed from the Gemfile.

**Comment by omnistegan** [comment]
Thanks @mamhoff, I've made the requisite change in this commit: [0849287](https://github.com/omnistegan/solidus_responders/commit/0849287dd7fe39b7e871087a4ba962b4ddd4359e)
